FROM alpine

RUN apk upgrade --no-cache && apk add --no-cache 'libssl3' 'libcrypto3' 'sqlite'
RUN adduser --uid 1022 --disabled-password --system --no-create-home vniservice


COPY vni_service /opt/vni_service

RUN chmod +x /opt/vni_service
USER 1022:1022

ENTRYPOINT ["/opt/vni_service"]
CMD ["--file", "/opt/db/db.sqlite3", "--log"]
EXPOSE 8842