apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: vnis.horizon-opencube.eu
spec:
  group: horizon-opencube.eu
  names:
    kind: Vni
    plural: vnis
    shortNames:
      - vni
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                vni:
                  type: integer
      subresources:
        status: { }