apiVersion: metacontroller.k8s.io/v1alpha1
kind: DecoratorController
metadata:
  name: vni-autovni-controller
  namespace: vni-management
spec:
  resources:
    - apiVersion: apps/v1
      resource: deployments
      annotationSelector:
        matchExpressions:
          - {key: vni, operator: Exists}
    - apiVersion: apps/v1
      resource: daemonsets
      annotationSelector:
        matchExpressions:
          - {key: vni, operator: Exists}
    - apiVersion: apps/v1
      resource: replicasets
      annotationSelector:
        matchExpressions:
          - {key: vni, operator: Exists}
    - apiVersion: batch/v1
      resource: jobs
      annotationSelector:
        matchExpressions:
          - { key: vni, operator: Exists }
    - apiVersion: batch.volcano.sh/v1alpha1
      resource: jobs
      annotationSelector:
        matchExpressions:
          - { key: vni, operator: Exists }

    - apiVersion: horizon-opencube.eu/v1
      resource: vniclaims
  attachments:
    - apiVersion: horizon-opencube.eu/v1
      resource: vnis
  hooks:
    sync:
      webhook:
        url: http://vni-endpoint-service.vni-management:8842/sync
    finalize:
      webhook:
        url: http://vni-endpoint-service.vni-management:8842/finalize